chore: hopefully final touches to README
momentohq/client-sdk-dotnet pull request #304
Opened 2022-10-12 00:27 UTC by cprice404

Tweaks the ordering of the README sections a bit to make the
examples more prominent and highlight the pattern matching
earlier.

Also adds an initial doc for advanced configuration.

The README template generator will need to be tweaked to
accommodate these changes but this feels like a better
structure based on the feedback we got in the bug bash.

2022-10-12 00:43 UTC, pgautier404 submitted a review, later dismissed
LGTM

2022-10-12 16:19 UTC, poppoerika submitted a review, later dismissed

2022-10-13 17:48 UTC, eaddingtonwhite submitted a review, later dismissed
Looks great 👍 🚢

2022-10-13 22:27 UTC, malandis requested changes

2022-10-13 22:27 UTC, malandis commented on docs/advanced-config.md
> +)
The constructor requires `authProvider` and `defaulTtl` too

```suggestion
new SimpleCacheClient(
    Configurations.InRegion.Default.Latest().WithClientTimeout(TimeSpan.FromSeconds(2)),
    authProvider,
    defaultTtl
)
```

2022-10-13 22:44 UTC, malandis approved these changes

2022-10-13 22:55 UTC, merged