chore: update examples to use CacheClient instead of SimpleCacheClient
momentohq/client-sdk-dotnet pull request #402
Opened 2023-03-09 17:53 UTC by cprice404

For early review.  Need to get rid of the csproj changes once we have a release that contains the new name.

2023-03-09 21:42 UTC, malandis submitted a review, later dismissed

2023-03-14 15:06 UTC, allenheltondev commented on tests/Unit/Momento.Sdk.Tests/CacheClientConstructorTest.cs
> +    const String TEST_AUTH_TOKEN = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb29Abm90LmEuZG9tYWluIiwiY3AiOiJjb250cm9sLXBsYW5lLWVuZHBvaW50Lm5vdC5hLmRvbWFpbiIsImMiOiJjYWNoZS1lbmRwb2ludC5ub3QuYS5kb21haW4ifQo.rt
Shouldn't this be an environment variable or some other substituted value so we don't check an auth token into source control?

2023-03-14 15:06 UTC, allenheltondev requested changes
What is the convention for using test auth tokens? I don't think we should check one into source control.

2023-03-21 22:27 UTC, malandis approved these changes

2023-03-21 22:29 UTC, merged